
version: 2
jobs:
  build:
    docker:
      - image: python:3.5
    working_directory: /home/ubuntu/working
    steps:
        - checkout
        - run: pip install -U -r requirements.txt
        - run: python setup.py sdist
        - run: pip install twine
        - run: twine upload dist/*