version: 2
jobs:
  build:
    docker:
      - image: egis/ubuntu-base
    working_directory: /home/ubuntu/working
    steps:
        - run: apt-get update -y && apt-get install -y nsis
        - run: pip install twine pynsist
        - checkout
        - run: sed -i.bak s/{{BUILD_NUMBER}}/$CIRCLE_BUILD_NUM/g installer.cfg
        - run: sed -i.bak s/{{BUILD_NUMBER}}/$CIRCLE_BUILD_NUM/g setup.py
        - run: pip install dox
        - run: dox
        - run: pip install -U -r requirements.txt
        - run: python setup.py sdist
        - run: twine upload dist/*
        - run: pynsist installer.cfg
        - store_artifacts:
            path: build/nsis/papertrail-cli-setup.exe